### ISSUE TITLE
Some form of public key crypto?

### ISSUE THREAD

**Issue by ivoras** [intrbiz/arduino-crypto#11]
Hello!

Thank you for making this, it's a neat and compact library! Just as a suggestion, of course, if you have the time and inspiration to do it, maybe it would be useful to add some form of public key crypto to the library? Elliptic curve (ECC) is much used to day and fairly well documented.

In any case, thank you and best of luck!

**Comment by intrbiz** [comment]
Whilst this would be a great idea, especially if the ESP8266 and ESP32 hardware acceleration could be used.  I don't really have a use case for it in my projects and no time to implement such a feature.  Any contributions would be welcome though.
